# "$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# Default keymaps
# https://github.com/sxyazi/yazi/blob/latest/yazi-config/preset/keymap.toml

# https://yazi-rs.github.io/docs/configuration/keymap

[manager]
search = "fd"


[[manager.prepend_keymap]]
on = ["q"]
run = "plugin projects quit"
desc = "保存最后项目并退出进程"

[[manager.prepend_keymap]]
on = [";"]
run = '''shell "$SHELL" --block --confirm'''
desc = "打开终端"

[[manager.prepend_keymap]]
on = ["?"]
run = "help"
desc = "显示帮助"

[[manager.prepend_keymap]]
on = ["<C-t>"]
run = "tab_create"
desc = "新标签"

[[manager.prepend_keymap]]
on = ["w", "t"]
run = "tab_create"
desc = "新标签"

[[manager.prepend_keymap]]
on = ["<C-w>"]
run = "tab_close"
desc = "关闭当前标签页"

[[manager.prepend_keymap]]
on = ["w", "x"]
run = "tab_close"
desc = "关闭当前标签页"

[[manager.prepend_keymap]]
on = ["w", "p"]
run = "plugin --sync preview-visibility toggle"
desc = "显示/隐藏预览"

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

# [[manager.prepend_keymap]]
# on = ["f", "s"]
# run = "search fd"
# desc = "Search files by name using fd"


[[manager.prepend_keymap]]
on = ["f", "d"]
run = "plugin fg fzfd"
# run = "search fd"
desc = "搜索目录"

# [[manager.prepend_keymap]]
# on = ["f", "g"]
# run = "plugin fg"
# desc = "find file by content (fuzzy match)"

# [[manager.prepend_keymap]]
# on = ["f", "G"]
# run = "plugin fg --args='rg'"
# desc = "find file by content (ripgrep match)"

[[manager.prepend_keymap]]
on = ["f", "n"]
run = "plugin fg fzf"
desc = "全部搜索"

[[manager.prepend_keymap]]
on = ["f", "f"]
run = "plugin fg fzfc"
desc = "搜索文件名"

[[manager.prepend_keymap]]
on = ["f", "F"]
run = "plugin smart-filter"
desc = "过滤列表"

[[manager.prepend_keymap]]
on = ["<C-Enter>"]
run = "open --interactive --hover"
desc = "Show context menu for hovered file"

[[manager.prepend_keymap]]
on = ["q"]
run = "plugin --sync nvim quit"
desc = "Quit"

[[manager.prepend_keymap]]
on = ["<Enter>"]
run = "plugin --sync nvim open"
desc = "Open"

[[manager.prepend_keymap]]
on = ["<S-Up>"]
run = "plugin --sync nvim 'scroll-preview -5'"
desc = "Seek up 5 units in the preview"

[[manager.prepend_keymap]]
on = ["<S-Up>"]
run = "plugin --sync nvim 'scroll-preview -5'"
desc = "Seek up 5 units in the preview"

[[manager.prepend_keymap]]
on = ["<S-Down>"]
run = "plugin --sync nvim 'scroll-preview 5'"
desc = "Seek down 5 units in the preview"

[[manager.prepend_keymap]]
on = "y"
run = ["""
  shell '
  if [[ "$OSTYPE" == "darwin"* ]]; then
      cat "$@" | pbcopy
  elif command -v xclip >/dev/null 2>&1; then
      cat "$@" | xclip -selection clipboard
  elif command -v xsel >/dev/null 2>&1; then
      cat "$@" | xsel --clipboard --input
  else
      echo "No clipboard command found. Please install xclip or xsel."
      exit 1
  fi
  '
  """, "yank"]
desc = "Copy file contents to clipboard"

[[manager.append_keymap]]
on = ["l"]
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.append_keymap]]
on = ["e"]
run = "open"
desc = "Selected"

[[manager.append_keymap]]
on = ["E"]
run = "open --interactive"
desc = "Selected interactively"

[[manager.append_keymap]]
on = ["g", "n"]
run = "cd ~/.config/nvim/"
desc = "NVIM"

[[manager.append_keymap]]
on = ["g", "d"]
run = "cd ~/documents/"
desc = "Docsuments"

[[manager.append_keymap]]
on = ["g", "/"]
run = "cd ~/dotfiles/"
desc = "Dotfiles"

[[manager.append_keymap]]
on = ["g", "o"]
run = "cd '$HOME/Library/Mobile Documents/iCloud~md~obsidian/Documents'"
desc = "Obsidian"

[[manager.append_keymap]]
on = ["g", "."]
run = "cd ~/.config/"
desc = "Config"

[[manager.prepend_keymap]]
on = ["g", "c"]
run = "cd ~/Code/"
desc = "Code"

[[manager.append_keymap]]
on = ["g", "G"]
run = "plugin lazygit"
desc = "Lazygit"

[[manager.append_keymap]]
on = ["g", "r"]
run = '''
	shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"' --confirm
'''
desc = "back to the root of the current Git repository"

# projects
[[manager.prepend_keymap]]
on = ["P", "s"]
run = "plugin projects save"
desc = "保存当前方案"

[[manager.prepend_keymap]]
on = ["P", "l"]
run = "plugin projects load"
desc = "加载当前方案"

[[manager.prepend_keymap]]
on = ["P", "P"]
run = "plugin projects load_last"
desc = "加载最后一个方案"

[[manager.prepend_keymap]]
on = ["P", "d"]
run = "plugin projects delete"
desc = "删除当前项目"

[[manager.prepend_keymap]]
on = ["P", "D"]
run = "plugin projects delete_all"
desc = "删除所有项目"

[[manager.prepend_keymap]]
on = ["P", "m"]
run = "plugin projects merge current"
desc = "合并当前项目到其他项目"

[[manager.prepend_keymap]]
on = ["P", "M"]
run = "plugin projects merge all"
desc = "合并当前项目到所有项目"
# projects end

[tasks]
prepend_keymap = [{ on = ["<F1>"], run = "close", desc = "Close task manager" }]

[input]
prepend_keymap = [
  { on = [
    "<Esc>",
  ], run = "close", desc = "Abort input" },
  { on = [
    "<C-Backspace>",
  ], run = "kill backward", desc = "Backspace word" },
]

[help]
prepend_keymap = [
  { on = ["<PageUp>"], run = "arrow -20", desc = "Move up n lines" },
  { on = ["<PageDown>"], run = "arrow 20", desc = "Move down n lines" },
  { on = ["<Home>"], run = "arrow -10000", desc = "Move to the beginning" },
  { on = ["<End>"], run = "arrow 10000", desc = "Move to the end" },
  # { on = [
  #   "<C-/>",
  # ], run = "close", desc = "Close help" },
]
