# "$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# Default keymaps
# https://github.com/sxyazi/yazi/blob/latest/yazi-config/preset/keymap.toml

# https://yazi-rs.github.io/docs/configuration/keymap

[manager]
search = "fd"
prepend_keymap = [
  { on = [
    ";",
  ], run = '''shell "$SHELL" --block --confirm''', desc = "Open shell here" },
  { on = [
    "?",
  ], run = "help", desc = "Show help" },
  { on = [
    "<C-t>",
  ], run = "tab_create", desc = "New tab" },
  { on = [
    "<C-w>",
  ], run = "tab_close", desc = "Close current tab" },
  { on = [
    "t",
  ], run = "plugin --sync preview-visibility --args=toggle", desc = "Show/hide preview" },
  { on = [
    "c",
    "m",
  ], run = "plugin chmod", desc = "Chmod on selected files" },
  { on = [
    "f",
    "s",
  ], run = "search fd", desc = "Search files by name using fd" },
  { on = [
    "f",
    "g",
  ], run = "plugin fg", desc = "find file by content (fuzzy match)" },
  { on = [
    "f",
    "G",
  ], run = "plugin fg --args='rg'", desc = "find file by content (ripgrep match)" },
  { on = [
    "f",
    "n",
  ], run = "plugin fg --args='fzf'", desc = "find file by filename" },
  { on = [
    "f",
    "f",
  ], run = "filter --smart", desc = "Filter files" },
  { on = [
    "f",
    "F",
  ], run = "plugin smart-filter", desc = "Smart Filter" },
  { on = [
    "<C-Enter>",
  ], run = "open --interactive --hover", desc = "Show context menu for hovered file" },
  { on = [
    "q",
  ], run = "plugin --sync nvim --args=quit", desc = "Quit" },
  { on = [
    "<Enter>",
  ], run = "plugin --sync nvim --args=open", desc = "Open" },
  { on = [
    "<S-Up>",
  ], run = "plugin --sync nvim --args='scroll-preview -5'", desc = "Seek up 5 units in the preview" },
  { on = [
    "<S-Down>",
  ], run = "plugin --sync nvim --args='scroll-preview 5'", desc = "Seek down 5 units in the preview" },
]


append_keymap = [
  { on = [
    "e",
  ], run = "open", desc = "Selected" },
  { on = [
    "E",
  ], run = "open --interactive", desc = "Selected interactively" },
  { on = [
    "g",
    "n",
  ], run = "cd ~/.config/nvim/", desc = "NVIM" },
  { on = [
    "g",
    "D",
  ], run = "cd ~/documents/", desc = "Docsuments" },
  { on = [
    "g",
    "/",
  ], run = "cd ~/dotfiles/", desc = "Dotfiles" },
  { on = [
    "g",
    "o",
  ], run = "cd '$HOME/Library/Mobile Documents/iCloud~md~obsidian/Documents'", desc = "Obsidian" },
  { on = [
    "g",
    ".",
  ], run = "cd ~/.config/", desc = "Config" },
  { on = [
    "g",
    "c",
  ], run = "cd ~/Code/", desc = "Code" },
]


[tasks]
prepend_keymap = [{ on = ["<F1>"], run = "close", desc = "Close task manager" }]

[input]
prepend_keymap = [
  { on = [
    "<Esc>",
  ], run = "close", desc = "Abort input" },
  { on = [
    "<C-Backspace>",
  ], run = "kill backward", desc = "Backspace word" },
]

[help]
prepend_keymap = [
  { on = ["<PageUp>"], run = "arrow -20", desc = "Move up n lines" },
  { on = ["<PageDown>"], run = "arrow 20", desc = "Move down n lines" },
  { on = ["<Home>"], run = "arrow -10000", desc = "Move to the beginning" },
  { on = ["<End>"], run = "arrow 10000", desc = "Move to the end" },
  # { on = [
  #   "<C-/>",
  # ], run = "close", desc = "Close help" },
]
